/**
 * BuildingBugAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param nome 
 * @param apelido 
 * @param email 
 * @param senha 
 * @param contacto 
 */
data class CreateClienteRequestContract (

    val nome: kotlin.String,
    val apelido: kotlin.String,
    val email: kotlin.String,
    val senha: kotlin.String,
    val contacto: kotlin.Int
) {
}