/**
 * BuildingBugAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param morada 
 * @param dataInicio 
 * @param fator 
 * @param clienteId 
 * @param codigoPostalCP 
 * @param profissionalId 
 * @param tipoId 
 */
data class CreateServicoRequestContract (

    val morada: kotlin.String,
    val dataInicio: java.time.LocalDateTime,
    val fator: kotlin.Int,
    val clienteId: kotlin.Int,
    val codigoPostalCP: kotlin.Int,
    val profissionalId: kotlin.Int,
    val tipoId: kotlin.Int
) {
}