/**
 * BuildingBugAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param &#x60;data&#x60; 
 * @param servicoId 
 * @param detalhes 
 */
data class CreateDeslocacaoRequestContract (

    val `data`: java.time.LocalDateTime? = null,
    val servicoId: kotlin.Int? = null,
    val detalhes: kotlin.String? = null
) {
}