/**
 * BuildingBugAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param descricao 
 */
data class UpdateEstadoServicoRequestContract (

    val id: kotlin.Int? = null,
    val descricao: kotlin.String? = null
) {
}