/**
 * BuildingBugAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param morada 
 * @param dataInicio 
 * @param dataFim 
 * @param avaliacao 
 * @param custo 
 * @param fator 
 * @param clienteId 
 * @param estadoServicoId 
 * @param codigoPostalCP 
 * @param profissionalId 
 * @param tipoId 
 */
data class UpdateServicoRequestContract (

    val id: kotlin.Int,
    val morada: kotlin.String,
    val dataInicio: java.time.LocalDateTime,
    val dataFim: java.time.LocalDateTime,
    val avaliacao: kotlin.Int,
    val custo: kotlin.Float,
    val fator: kotlin.Int,
    val clienteId: kotlin.Int,
    val estadoServicoId: kotlin.Int,
    val codigoPostalCP: kotlin.Int,
    val profissionalId: kotlin.Int,
    val tipoId: kotlin.Int
) {
}