/**
 * BuildingBugAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.CreateDeslocacaoRequestContract
import io.swagger.client.models.UpdateDeslocacaoRequestContract

import io.swagger.client.infrastructure.*

class DeslocacaoApi(basePath: kotlin.String = "/") : ApiClient(basePath) {

    /**
     * Obter todas as deslocações
     * 
     * @param version  
     * @return void
     */
    fun apiVversionDeslocacaoAllGet(version: kotlin.String): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v{version}/Deslocacao/all".replace("{" + "version" + "}", "$version")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Eliminar uma deslocação
     * 
     * @param id  
     * @param version  
     * @return void
     */
    fun apiVversionDeslocacaoDeleteIdDelete(id: kotlin.Int, version: kotlin.String): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/api/v{version}/Deslocacao/delete/{id}".replace("{" + "id" + "}", "$id").replace("{" + "version" + "}", "$version")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Obter uma deslocação
     * 
     * @param id  
     * @param version  
     * @return void
     */
    fun apiVversionDeslocacaoIdGet(id: kotlin.Int, version: kotlin.String): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v{version}/Deslocacao/{id}".replace("{" + "id" + "}", "$id").replace("{" + "version" + "}", "$version")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Marcar uma Deslocação
     * 
     * @param version  
     * @param body  (optional)
     * @return void
     */
    fun apiVversionDeslocacaoNewPost(version: kotlin.String, body: CreateDeslocacaoRequestContract? = null): Unit {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/v{version}/Deslocacao/new".replace("{" + "version" + "}", "$version")
        )
        val response = request<Any?>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Atualizar uma deslocação
     * 
     * @param version  
     * @param body  (optional)
     * @return void
     */
    fun apiVversionDeslocacaoUpdatePut(version: kotlin.String, body: UpdateDeslocacaoRequestContract? = null): Unit {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/api/v{version}/Deslocacao/update".replace("{" + "version" + "}", "$version")
        )
        val response = request<Any?>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
